//######## Variable

//#1
// Welcome to Thailand
/* You are so aborable*/

//#2
var myName;

//#3
// Setup
var a;
a=7;
// Only change code below this line

//#4
// Setup
var a;
a = 7;
var b;
b=a;
// Only change code below this line


//#5 Initializing Variables with the Assignment Operator
var a=9;

//#6 Understanding Uninitialized Variables
// Only change code below this line
var a=5;
var b=10;
var c="I am a";
// Only change code above this line

a = a + 1;
b = b + 5;
c = c + " String!";

//#7 Understanding Case Sensitivity in VariablesPassed
// Variable declarations
var studlyCapVar;
var properCamelCase;
var titleCaseOver;

// Variable assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

//########### Number
//#8 Add Two Numbers with JavaScript
var sum = 10 + 10;

//#9 Subtract One Number from Another with JavaScript
var difference = 45 - 33;

//#10 Multiply Two Numbers with JavaScript
var product = 8 * 10;

//#11 Divide One Number by Another with JavaScript
var quotient = 66 / 33;

//#12 Increment a Number with JavaScript
var myVar = 87;

// Only change code below this line
myVar++;

//#13 Decrement a Number with JavaScript
var myVar = 11;

// Only change code below this line
myVar--;

//#14 Create Decimal Numbers with JavaScript
//var ourDecimal = 5.7;

// Only change code below this line

var myDecimal = 3.3;

//#15 Multiply Two Decimals with JavaScript
var product = 2.0 * 2.5;

//#16 Divide One Decimal by Another with JavaScript
var quotient = 4.4 / 2.0; // Change this line

//#17 Finding a Remainder in JavaScript
// Only change code below this line

var remainder;
remainder = 11%3;

//#18 Compound Assignment With Augmented Addition
var a = 3;
var b = 17;
var c = 12;

// Only change code below this line
a += 12;
b += 9;
c += 7;

//#19 Compound Assignment With Augmented Subtraction
var a = 11;
var b = 9;
var c = 3;

// Only change code below this line
a -= 6;
b -= 15;
c -= 1;

//#20 Compound Assignment With Augmented Multiplication
var a = 5;
var b = 12;
var c = 4.6;

// Only change code below this line
a *= 5;
b *= 3;
c *= 10;

//#21 Compound Assignment With Augmented Division
var a = 48;
var b = 108;
var c = 33;

// Only change code below this line
a /=  12;
b /= 4;
c /= 11;

//#22 Declare String Variables
let myFirstName = 'Thanawat';
let myLastName = 'Pibunnirote';

//#23 Escaping Literal Quotes in Strings
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

//#24 Quoting Strings with Single Quotes
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';

//#25 Escape Sequences in Strings
var myStr='FirstLine\n\t\\SecondLine\nThirdLine'; // Change this line

//#26 Concatenating Strings with Plus Operator
var myStr='This is the start. '+'This is the end.'; // Change this line

//#27 Concatenating Strings with the Plus Equals Operator
// Only change code below this line

var myStr='This is the first sentence. ';
myStr += 'This is the second sentence.';

//#28 Constructing Strings with Variables
// Only change code below this line
var myName='Thanawat';
var myStr='My name is '+ myName + ' and I am well!!';

//#29 Appending Variables to Strings
// Change code below this line

var someAdjective='abc';
var myStr = "Learning to code is ";
myStr += someAdjective;

//#30 Find the Length of a String
// Setup
var lastNameLength = 0;
var lastName = "Lovelace";

// Only change code below this line

lastNameLength = lastName.length;

//#31 Use Bracket Notation to Find the First Character in a String
// Setup
var firstLetterOfLastName = "";
var lastName = "Lovelace";

// Only change code below this line
firstLetterOfLastName = lastName[0]; // Change this line

//#32 Understand String Immutability
// Setup
var myStr = "Jello World";

// Only change code below this line
myStr = "Hello World"; // Change this line
// Only change code above this line

//#33 Use Bracket Notation to Find the Nth Character in a String
// Setup
var lastName = "Lovelace";

// Only change code below this line
var thirdLetterOfLastName = lastName[2]; // Change this line

//#34 Use Bracket Notation to Find the Last Character in a String
// Setup
var lastName = "Lovelace";

// Only change code below this line
var lastLetterOfLastName = lastName[lastName.length-1]; // Change this line

//#35 Use Bracket Notation to Find the Nth-to-Last Character in a String
// Setup
var lastName = "Lovelace";

// Only change code below this line
var secondToLastLetterOfLastName = lastName[lastName.length-2]; // Change this line

//#36 Word Blanks
var myNoun = "dog";
var myAdjective = "big";
var myVerb = "ran";
var myAdverb = "quickly";

// Only change code below this line
var wordBlanks = myAdjective+" "+myNoun+" "+myVerb+" "+myAdverb+"."; // Change this line
// Only change code above this line











